version: "3.8"
services:
  server:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./server
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL:${DATABASE_URL}
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    restart: always
  client:
    container_name: client
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
volumes:
  postgres_data:


