version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app


